### ISSUE TITLE
stripe-sdk works only with flutter beta

### ISSUE THREAD

**Issue by devapalanisamy** [ezet/stripe-sdk#106]
I get the below error If I use stripe-sdk with flutter stable.

`../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_sdk-4.0.2/lib/src/ui/screens/payment_methods_screen.dart:151:39: Error: The getter 'ScaffoldMessenger' isn't defined for the class 'PaymentMethodsList'.
 - 'PaymentMethodsList' is from 'package:stripe_sdk/src/ui/screens/payment_methods_screen.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_sdk-4.0.2/lib/src/ui/screens/payment_methods_screen.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
                                      ScaffoldMessenger.of(rootContext).showSnackBar(SnackBar(
                                      ^^^^^^^^^^^^^^^^^
2

FAILURE: Build failed with an exception.

* Where:
Script '/Users/deva/Documents/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/deva/Documents/Development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights`

If I switch to beta channel, this error is gone.

**Comment by funder7** [comment]
Thanks, I was facing the same problem. Is there any workaround except of switching to beta?

**Comment by devapalanisamy** [comment]
If you use only non-ui part of the package, you can import the model directly instead of importing stripe_sdk_ui.

I replace this `import 'package:stripe_sdk/stripe_sdk_ui.dart';` with this `import 'package:stripe_sdk/src/models/card.dart';`

This works only if you don't use experimental UI.

**Comment by ezet** [comment]
Will look into this 👍

**Comment by preteambuy** [comment]
any updates on this?

**Comment by p02diada** [comment]
any updates on this?

**Comment by josxha** [comment]
The problem was finally fixed with the release of flutter 2.
