### ISSUE TITLE
Creating token for the bank account

### ISSUE THREAD

**Issue by alexandersokol** [ezet/stripe-sdk#107]
Hello!

I'm trying to create a token for the Bank account using stripe SDK with the following code:

`
StripeApi.init('pk_test_my_token');
accountNumber = "000123456789"; // Test bank account
routingNumber = "110000000";

final data = <String, dynamic>{};
      data[_kCountry] = _kCountryUS;
      data[_kAccountNumber] = int.tryParse(accountNumber);
      data[_kRoutingNumber] = int.tryParse(routingNumber);

      final tokenResult = await StripeApi.instance.createToken(data);
`
I'm getting an error:
"You cannot use a live bank account number when making transfers or debits in test mode"

On the Stripe testing doc page, it is written to use test secret keys for test bank accounts.
https://stripe.com/docs/connect/testing

https://stripe.com/docs/api/tokens/create_bank_account?lang=curl
Could you please shed some light on where I can put my sk_test_* key to make test bank accounts work?

**Comment by ezet** [comment]
Is `000123456789` a Stripe test account? You can only add pre-defined test accounts in test mode. Basically, the problem is exactly what is stated in the error; "You cannot use a live bank account number when making transfers or debits in test mode".
