### ISSUE TITLE
backend question

### ISSUE THREAD

**Issue by joe-getcouragenow** [ezet/stripe-sdk#108]
Was looking at https://github.com/ezet/stripe-sdk-demo-api

SO the dart code calls this code, which then calls the strip server ?

I ask because i want to replace the firebase code with golang code so i dont need google firebase.

BTW thanks for making this flutter plugin. Having no native is a huge bonus, because we can then use it on web, desktop, mobile and embedded ( rasp pi, etc).

**Comment by ezet** [comment]
Yes, correct. Some calls are made directly from the library to Stripe, while other calls must be done from your own backend because they require the secret key. 
And thank you :)

**Comment by joe-getcouragenow** [comment]
Can i just confirm by using one of your examples please.

"confirmPayment" is called from https://github.com/ezet/stripe-sdk/blob/master/example/lib/ui/payment_screen.dart#L75, which is i presume being handled by this https://github.com/ezet/stripe-sdk-demo-api/blob/master/functions/src/handlers/confirmPaymentHandler.ts#L5 ?

SO the flutter code is calling the firebase function ?

**Comment by ezet** [comment]
Correct. The firebase function then calls the Stripe API, and returns the response to the flutter client.
