### ISSUE TITLE
mobile / web integration to call OS to get users credit cards installs at OS level

### ISSUE THREAD

**Issue by joe-getcouragenow** [ezet/stripe-sdk#109]
I suspect i am asking is question the wrong way, but ...

On web browsers, there are specific calls to ask the OS for the users credit card that the OS saves i presume in the TPM / Cert store, etc. 
Same goes for Mobile in many ways.

Since this is pure Dart, then i presume getting the users local cards is not possible ?

---

Braintree ( which paypal owns) seems to do it.... ?

https://pub.dev/packages/flutter_braintree

- calls this to get the users credit card rom OS ?
https://github.com/card-io

**Comment by ezet** [comment]
This functionality is out of scope for this library, but it might be possible to use other libraries to retrieve the required data, and then use that data with stripe sdk. I have not worked with these APIs so I don't know them well enough.

**Comment by ezet** [comment]
Not in scope of this library. You can use whichever approach you want to get card details, and then tokenize it with the tokenization methods this library offers, and proceed to use it with Stripe however you want.
