### ISSUE TITLE
web confirm payment bug

### ISSUE THREAD

**Issue by gorillatapstudio** [ezet/stripe-sdk#110]
In V4.0.2/stripe.dart L118
    final data = {'return_url': getReturnUrlForSca(**webReturnPath: _returnUrlForSca**)};
Adding the bold text fixed the failure of payment intent confirmation on web app.
Please verify. Thanks!

**Comment by ezet** [comment]
Not able to confirm right now, but it looks like I've forgotten to add this. Will check and update asap.

**Comment by varunbhalerao56** [comment]
> Not able to confirm right now, but it looks like I've forgotten to add this. I Will check and update asap.

Hey @ezet  any update on this, tried on the latest example the payment does not return success after authentication, and the data returned from the confirmed payment method is empty. @gorillatapstudio did try the above method but does not seem to work with the latest code.

**Comment by ezet** [comment]
@varunbhalerao56 You are talking about the web platform here, right? I am unfortunately not able to spend much time on the web platform right now. If anyone has ideas, please share them

**Comment by gauravmehta13** [comment]
@gorillatapstudio  @varunbhalerao56  @ezet   Hi guys, is this plugin working for web?

**Comment by varunbhalerao56** [comment]
> @gorillatapstudio @varunbhalerao56 @ezet Hi guys, is this plugin working for the web?

Hey, @gauravmehta13  I got to know the reason as to why it is not working. It is due to the uni_links package.

I have created an issue in that package but no response yet. I don't think there is a way to implement it easily unless this is solved.
https://github.com/avioli/uni_links/issues/117

In the end, I just switched to Stripe checkout instead.

**Comment by ezet** [comment]
Web support is now fully supported

**Comment by stylehuan** [comment]
> 

It's just an error

**Comment by stylehuan** [comment]
> 现在完全支持网络支持

It's just an error
