### ISSUE TITLE
The return URL for web is not setting correctly

### ISSUE THREAD

**Issue by HathTech** [ezet/stripe-sdk#118]
I have made the changes to my fork but thought to share it if anyone is facing the same issue. 

![Screenshot 2021-03-06 at 12 35 41 PM](https://user-images.githubusercontent.com/13694051/110201206-e73ab080-7e87-11eb-9850-cb5ef1d29cda.png)

**Comment by ezet** [comment]
I will fix this next week

**Comment by ezet** [comment]
Fixed
