### ISSUE TITLE
Confusion between Publishable key and Secret key

### ISSUE THREAD

**Issue by idrish-sorathiya** [ezet/stripe-sdk#121]
Hi,

Thanks for such a wonderful package. 

I was exploring a library and document of it. I found that everywhere we have used word Publishable key and at most of the places code documentation is saying "[publishableKey] is your publishable key, beginning with "sk_"....." however, publishable key starts from "pk_" and Secret key starts from "sk_". so, which key is expected by library to work smoothly.

**Comment by ezet** [comment]
Publishable key is the correct key to use. The secret key should definitely not be stored in the client.

**Comment by ezet** [comment]
Fixed.
