### ISSUE TITLE
Sound Null Safety Support

### ISSUE THREAD

**Issue by BirjuVachhani** [ezet/stripe-sdk#124]
Now that Dart's null safety is in stable, it is the right time to migrate this SDK to null safety.

**Comment by ezet** [comment]
Yes, this will be added in the next major release.

**Comment by ezet** [comment]
Fixed.

**Comment by BirjuVachhani** [comment]
@ezet Wonderful. Thanks. 👍🏻

**Comment by josxha** [comment]
Calling to reopen, as no stable null safety support exists on pub.dev yet.
