### ISSUE TITLE
iOS, a small safari back button is shown after the SCA returns back to the app

### ISSUE THREAD

**Issue by varunbhalerao56** [ezet/stripe-sdk#127]
Currently using the automatic payment intent and redirecting the user to the browser. After I click confirm (Fig 1) I return back to the application and there is a safari icon on the top left of the screen which allows me to go back to the safari browser (Fig 2). 

![image](https://user-images.githubusercontent.com/59999892/112300208-8c9cb380-8cd3-11eb-9bf0-ab6ef5d02e73.png)
![image](https://user-images.githubusercontent.com/59999892/112300553-f0bf7780-8cd3-11eb-965b-8bc0dbd50170.png)

Have tried tweaking the launch() in the stripe.dart but no luck. Not sure if this is an issue from the url_launcher.

**Comment by ezet** [comment]
@varunbhalerao56 Did you find a solution to this issue?
