### ISSUE TITLE
Method confirmSetupIntent of StripeApi throws UnsupportedError (ver. 5.0.0-nullsafety.0)

### ISSUE THREAD

**Issue by francislions** [ezet/stripe-sdk#129]
I'm trying to create and confirm a setup intent in the new version 5.0.0-mullsafety.0, but without success, the method _confirmSetupIntent_ of _StripeApi_ gives me this exception:
UnsupportedError (Unsupported operation: Cannot set value in unmodifiable Map)
The method _confirmSetupIntent_ is called with only the parameter _clientSecret_.
I'm using the _stripe_sdk_ from the 2.8.0, and i have even used the _confirmSetupIntent_ on version 4.0.2 and it always worked.
Do you know why there is this error?

**Comment by ezet** [comment]
I will look into this. @josxha Maybe you have any ideas?

**Comment by josxha** [comment]
My bad, I was not aware that the map becomes unmodifiable when I assign a default value to it.
Created https://github.com/ezet/stripe-sdk/pull/130
