### ISSUE TITLE
Crash on iOS 12 (Missing CoreNFC framework)

### ISSUE THREAD

**Issue by francislions** [ezet/stripe-sdk#131]
I'm trying to run the app on a iPhone with iOS 12.5.1.
The app immediately crash because of this error:

dyld: Library not loaded: /System/Library/Frameworks/CoreNFC.framework/CoreNFC Referenced from: /private/var/containers/Bundle/Application/87E45AEA-F9A7-4A7A-BBA3-2B2420EA2400/Runner.app/Frameworks/uni_links2.framework/uni_links2 Reason: image not found

I think the problem lies in the uni_links2 library, for some reason it needs CoreNFC, but for what i know from iOS 12 and below that framework isn't included.

**Comment by ezet** [comment]
Is anyone else experiencing this issue?

**Comment by diegogarciar** [comment]
@ezet I haven't tested on that iOS, but I submitted my app and Apple required me to provide explanation for the usage for NFC with a video. I then realized it was uni_links2 was the culprit but I have no intention on using it. 

I was using `uni_links` too but took your idea to use `uni_links2` for null safety support. I had to fork `uni_links2` to remove NFC and then forked your project to point `uni_links2` to my repo, a big mess. 

I actually came here bearing good news, uni_links has just updated to null safety, so I would really appreciate if you could go back to using the original `uni_links` package

**Comment by ezet** [comment]
Fixed
