### ISSUE TITLE
Publish bug-free version to pub.dev

### ISSUE THREAD

**Issue by josxha** [ezet/stripe-sdk#138]
Hi @ezet, I have just seen that many users experience problems with the package, as there is no current version available via pub.dev that is without errors.

The current stable release on pub.dev `4.0.2` has the following critical problem:
*Project not compile after adding package* https://github.com/ezet/stripe-sdk/issues/134

and the prerelease version `5.0.0-nullsafety.0` has this problem:
*Method confirmSetupIntent of StripeApi throws UnsupportedError* https://github.com/ezet/stripe-sdk/pull/130

---
You said:
> I won't release another version to pub yet, so I suggest you pull the library from git for now. https://github.com/ezet/stripe-sdk/pull/130#issuecomment-806714224

However, there is already an issue from users who are not aware of this because it is not documented anywhere: https://github.com/ezet/stripe-sdk/issues/134

Using the master branch of Github is also not practical, as this is used for development. Errors can occur here, as happened in issue https://github.com/ezet/stripe-sdk/issues/132.

**I therefore suggest again to publish another stable prerelease on `pub.dev` so that users encounter problems less often.**
As far as I have seen, there are no known bugs in the https://github.com/ezet/stripe-sdk/tree/617e34ce36bba3428a244525647522dd2e62a072 version, for example.

**Comment by josxha** [comment]
https://github.com/ezet/stripe-sdk/issues/131#issuecomment-828712632
> [...] I submitted my app and Apple required me to provide explanation for the usage for NFC with a video. I then realized it was uni_links2 was the culprit but I have no intention on using it.
> I was using `uni_links` too but took your idea to use `uni_links2` for null safety support. I had to fork `uni_links2` to remove NFC and then forked your project to point `uni_links2` to my repo, a big mess.
> I actually came here bearing good news, uni_links has just updated to null safety, so I would really appreciate if you could go back to using the original `uni_links` package

In this context, **uni_links2** could also be changed back to **uni_links**.

**Comment by ezet** [comment]
master has been updated a lot, but at this point it's more of an internal project. I'll consider releasing a new version when I have time
