### ISSUE TITLE
RangeError using DEFAULT_API_VERSION error retrieving ephemeral key

### ISSUE THREAD

**Issue by justoke** [ezet/stripe-sdk#146]
According to my Stripe dashboard the API version is 2020-08-27, whereas the DEFAULT_API_VERSION is 2020-03-02. I get the following error on startup using the example Flutter app. Is there a way to specify the API version as part of the initialization?

![image](https://user-images.githubusercontent.com/26506785/127044398-9dccf52d-9dec-42e0-9947-1e1880de79eb.png)

**Comment by ezet** [comment]
It's possible to specify API version if you manually instantiate the API client.
