### ISSUE TITLE
Credit Card Number AutofillHints.creditCardNumber shows full keyboard on iOS

### ISSUE THREAD

**Issue by justoke** [ezet/stripe-sdk#148]
In the CardNumberFormField component  there seems to be an issue with the interpretation of the input format as defined by AutofillHints.creditCardNumber. On Android devices a numeric keypad is displayed as expected, however on iOS devices the full keyboard is shown. To test this, I used the AutofillHints.telephoneNumber for the autofillHints and this correctly shows the numeric keypad in both Android and iOS.

flutter\.pub-cache\hosted\pub.dartlang.org\stripe_sdk-5.0.0-nullsafety.0\lib\src\ui\widgets\card_number_form_field.dart

![image](https://user-images.githubusercontent.com/26506785/145728434-798ecc1f-195d-4fc0-9524-9ccde2c0c791.png)

![image](https://user-images.githubusercontent.com/26506785/145728050-2767c9c4-4965-4005-ba78-08876857b7df.png)

iOS
![image](https://user-images.githubusercontent.com/26506785/145730285-141558aa-1f39-4940-9ead-5187f639ac38.png)

**Comment by ezet** [comment]
Working on a fix
