### ISSUE TITLE
Update dependencies to latest versions

### ISSUE THREAD

**Issue by vinnytwice** [ezet/stripe-sdk#149]
I'm trying to integrate stripe-sdk in my project but the actual version depends on old versions as `http: ^0.12.2` while other packages I use are depending  on newer versions for example..

 `http: ^0.12.2` ->`http: ^0.13.4`, ` url_launcher: ^5.7.10`  -> `url_launcher: ^6.0.12`,  `flutter_slidable: ^0.5.7` -> `flutter_slidable: ^0.6.0`.
 
 Any way to bypass this while the package has not updated to latest dependencies versions?

**Comment by vinnytwice** [comment]
after reading https://github.com/ezet/stripe-sdk/issues/134#issuecomment-847736659 I just add it to my yaml file as
´´´
stripe_sdk:
    git:
      url: git://github.com/ezet/stripe-sdk.git

```

**Comment by jbryanh** [comment]
Ditto, thanks for update.

**Comment by ezet** [comment]
Done
