### ISSUE TITLE
Question about PCI compliance 

### ISSUE THREAD

**Issue by Isakdl** [ezet/stripe-sdk#16]
Since this plugin calls the stripe API directly, as I understand it users of this package would have to submit the most extensive type of PCI compliance documents, this one: https://www.pcisecuritystandards.org/documents/PCI-DSS-v3_2_1-SAQ-D_Merchant.pdf

https://stripe.com/docs/security#validating-pci-compliance

Do I understand this correctly? If so there should probably be a warning or information about that in the readme.

**Comment by ezet** [comment]
Actually, I'm not quite sure. If you send any card data to your own backend, then you definitely fall under the most extensive type of PCI compliance. But if you use the tokenization methods (and you should) to tokenize the card data first, and submit that to your backend, I think you can argue that it doesn't apply because you have never received or processed the data. But I am not entirely sure!

**Comment by ezet** [comment]
A possible solution, if this is an issue, would be to rely on the native SDKs just for the tokenization methods. Even when using the native SDKs you are allowed to manually collect the card details on the device using your own methods. The important part is that the card details should never leave the device.

**Comment by Isakdl** [comment]
> Stripe’s mobile SDK development and change control is done in accordance with PCI DSS (requirements 6.3 - 6.5) and is delivered via our PCI validated systems. As such, we advise our users to rely on our official SDKs for iOS or Android, or to build a payment form with Elements in a WebView, to be eligible for the simplest form of PCI validation: SAQ A. If you only use our mobile SDKs or an Elements-based WebView, you can inform your PCI auditor that card numbers pass directly from your customers to Stripe.

> Should you do otherwise, such as writing your own code to send card information to the Stripe API, you may be responsible for additional PCI DSS requirements (6.3 - 6.5) and not be eligible for an SAQ A. In this case, we’d suggest you reach out to a PCI Qualified Security Assessor (QSA) to determine how best to validate your compliance according to the current guidance from the PCI Council.

And

> We strongly discourage passing card information directly to Stripe’s API as it means your integration is directly handling card information. Even if you do not store any payment information, we can only help simplify PCI compliance if you’ve integrated with Checkout, Elements, or our mobile SDKs.

> If you continue to send card details directly to our API, you’ll be required to upload your SAQ D annually to prove your business is PCI compliant. SAQ D is the most onerous of all the SAQs, with over 40 pages of requirements you must implement to remain PCI compliant. We highly recommend you migrate to client-side tokenization of card information to substantially reduce the scope of your PCI compliance.

Source: https://stripe.com/docs/security#validating-pci-compliance

To me it does indeed sound like you would have to pass the card details with the SDK unless you want to complete the SAQ D document. But that workaround might be enough.

**Comment by Isakdl** [comment]
I had a chat with the stripe developer support and got this response: 

> I had some discussions here and the best way forward would be to use the Stripe SDK CardInputWidget, this could be wrapped as you see fit in your app implementation while adhering to the PCI compliance standards.

and when I asked if it is out of the question to use my own form

>I don't think it's totally out of the question, but I'm not sure about the PCI compliance adherence of your app  if you opt-out of using Stripe owned SDK/Elements which are PCI compliant

So it does seem a bit dicey in my opinion.

**Comment by Isakdl** [comment]
@ezet Have you used this package in a production environment? If so you should have encountered the PCI issue if there is one. Stripes makes a review of your implementation after 20 transactions and determine what you need to do.

**Comment by ezet** [comment]
I have an app, but it's not in production yet. I'd like to find a solution to this tho, and will help in any way I can. I take it you have encountered this issue in production?

**Comment by Isakdl** [comment]
I do not yet have the payment solution in production, so no I have not encountered this issue. I only encountered it by accident reading up on PCI compliance.

Sent a message the to PCI team at Stripe and got the following response:

> As long as you serve your payment pages over TLS (https), and exclusively use either Stripe Elements [1], Checkout [2], or our official mobile libraries as the only way of handling card information, Stripe automatically creates a pre-filled Self-Assessment Questionnaire A (SAQ A) for you. If you’re eligible, you’ll find this on your PCI settings page here:
https://dashboard.stripe.com/account/compliance
If you’re collecting your customers’ card details in another way, we’ll ask that you complete and upload the appropriate questionnaire. You can find more details here:
https://stripe.com/docs/security#validating-pci-compliance
[1] https://stripe.com/docs/elements
[2] https://stripe.com/docs/checkout
I really hope this information provides suitable insight. If not, or if there is anything else I can help you with, just let me know.

Sadly this did not provide any new information. 

Are you sure it is okay to collect the card details in your own form if you still submit it with the SDK? To me, it seems that stripe cannot guarantee the implementation unless their code is used. Hence filling in the SAQ would be required. But with that said I'm not sure at all what to do here.

**Comment by ezet** [comment]
I am not sure, no. I will see what I can find about this, as I definitely don't want to cause unforeseen issues for users.

**Comment by JohnWhite777** [comment]
Hi there,
Probably I'm not the only person interested in what is PCI Compliance really is. I've  found this thread and decided to share some updated information. [Here’s](https://blog.verygoodsecurity.com/posts/what-is-pci-compliance/)  everything you need to know about PCI DSS and what it takes to obtain – and demonstrate – your company’s compliance. Hope this helps!
