### ISSUE TITLE
confirmPayment on Android showed the following error: HandshakeException: Handshake error in client (OS Error:  CERTIFICATE_VERIFY_FAILED: certificate is not yet valid

### ISSUE THREAD

**Issue by gorillatapstudio** [ezet/stripe-sdk#160]
Has anyone met the following issue?

When calling Stripe.instance.confirmPayment(..) on Android, I received the following error.

HandshakeException: Handshake error in client (OS Error: 
CERTIFICATE_VERIFY_FAILED: certificate is not yet valid

sttripe-sdk Version: ^5.0.0-nullsafety.1

I don't have this error before upgrading to v5. The whole checkout workflow works in iOS and Web. I did add the intent-filter to the MainActivity as instructed in the example.

**Comment by ezet** [comment]
SSL issue with your server
