### ISSUE TITLE
Any plans to support a card reader?

### ISSUE THREAD

**Issue by sgehrman** [ezet/stripe-sdk#17]
I want to access a card reader.  I tried Stripes android app, but it's buggy.  I don't think it looks that hard to implement, unfortunately the stripe javascript code is such a manged mess, it's not easy to figure out what it's doing, so it's not a easy port.  I may write this myself, but wanted to ask you first in case you had already done work on this.

**Comment by ezet** [comment]
No plans for supporting card readers, sorry.
