### ISSUE TITLE
Warnings with androidx

### ISSUE THREAD

**Issue by sgehrman** [ezet/stripe-sdk#18]
I enabled androidx and got this:

Launching lib/main.dart on Android SDK built for x86 in debug mode...
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/facebook/react/bridge/ReadableMap.java:42: warning: [unchecked] unchecked cast
            return new ReadableMap((Map<String, Object>) get(key));
                                                            ^
  required: Map<String,Object>
  found:    Object
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/gettipsi/stripe/util/Converters.java:527: warning: [deprecation] getCardInfo() in PaymentData has been deprecated
    if (paymentData != null && paymentData.getCardInfo() != null) {
                                          ^
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/gettipsi/stripe/util/Converters.java:528: warning: [deprecation] getCardInfo() in PaymentData has been deprecated
      return paymentData.getCardInfo().getBillingAddress();
                        ^
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/gettipsi/stripe/StripeModule.java:150: warning: [deprecation] TokenCallback in com.stripe.android has been deprecated
        new TokenCallback() {
            ^
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/gettipsi/stripe/StripeModule.java:147: warning: [deprecation] createToken(Card,String,ApiResultCallback<Token>) in Stripe has been deprecated
      mStripe.createToken(
             ^
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/gettipsi/stripe/StripeModule.java:174: warning: [deprecation] TokenCallback in com.stripe.android has been deprecated
        new TokenCallback() {
            ^
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/gettipsi/stripe/StripeModule.java:170: warning: [deprecation] createBankAccountToken(BankAccount,String,Executor,ApiResultCallback<Token>) in Stripe has been deprecated
      mStripe.createBankAccountToken(
             ^
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/gettipsi/stripe/StripeModule.java:211: warning: [deprecation] getFragmentManager() in Activity has been deprecated
      cardDialog.show(currentActivity.getFragmentManager(), "AddNewCard");
                                     ^
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/gettipsi/stripe/StripeModule.java:389: warning: [deprecation] SourceCallback in com.stripe.android has been deprecated
    mStripe.createSource(sourceParams, new SourceCallback() {
                                           ^
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:72: warning: [deprecation] newBuilder() in IsReadyToPayRequest has been deprecated
      IsReadyToPayRequest.newBuilder()
                         ^
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:133: warning: [deprecation] PaymentDataRequest.Builder in PaymentDataRequest has been deprecated
    PaymentDataRequest.Builder builder = PaymentDataRequest.newBuilder();
                      ^
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:133: warning: [deprecation] newBuilder() in PaymentDataRequest has been deprecated
    PaymentDataRequest.Builder builder = PaymentDataRequest.newBuilder();
                                                           ^
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:232: warning: [deprecation] getPaymentMethodToken() in PaymentData has been deprecated
            String tokenJson = paymentData.getPaymentMethodToken().getToken();
                                          ^
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:243: warning: [deprecation] getShippingAddress() in PaymentData has been deprecated
                paymentData.getShippingAddress(),
                           ^
/home/steve/google/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_payment-1.0.5/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:244: warning: [deprecation] getEmail() in PaymentData has been deprecated
                paymentData.getEmail()));
                           ^
15 warnings

**Comment by ezet** [comment]
That is from a different stripe library.
