### ISSUE TITLE
Deeplinking, url and seem buggy

### ISSUE THREAD

**Issue by Isakdl** [ezet/stripe-sdk#19]
I think it would be a good idea to be able to set the URL to use for deep linking as they should be unique.

Anyway, on android the link back from stripe seem to restart the app, this does not happen if you run `adb shell am start -W -a android.intent.action.VIEW -d "stripesdk://3ds.stripesdk.io"` in the terminal though.

On iOS I cannot get the linking to work at all, I have the data in info.plist as suggested by the readme.

Edit: Android only bugs with firefox not chrome... So the android error is probably not because of this plugin.

**Comment by ezet** [comment]
Hey! Sorry for the very late response here. Have you been able to get it working? I have tested and used it on Android extensively, but I have not had the chance to test it that much on iOS. I'd be more than willing to work out all iOS issues.

**Comment by Isakdl** [comment]
Hey! 

It works well on android if you use chrome, not sure what to do about firefox but that seems to be a specific browser problem, but perhaps there is a need to pass in params in the deep link, so that we at the very least can open the correct screen again. 

I still haven't gotten it to work on ios, you can rather easily navigate back manually though, so as an MVP it works.

I did, however, fork your code and added the ability to pass in my own url scheme. But was a quick hacky solution (setting the url at init). But I think that it could be a good idea to pass the url when calling "confirmSetupIntentWithPaymentMethod" and similar methods. That way the firefox issue could be "solved" (with url params).

**Comment by Isakdl** [comment]
The issue with firefox is that the app is launched as a new instance inside the firefox window, instead of actually going back to the app that is already running. Very weird behaviour.

**Comment by ezet** [comment]
The uri for deep linking should already be unique, as it has a random component. It needs this random component in order to support multiple installed apps with the SDK, and also because a single app can launch multiple browser sessions. The first issue can be solved by letting the developer supply a unique uri for their app, but it cause issues for the second scenario unless there is a random component to it. That is why I didn't expose an API for setting the uri. 

I can look at testing it for firefox and other browsers when I have time.

**Comment by vkmaxcooldude** [comment]
I faced the same issue, but in my case, even Google Chrome browser doesn't return the Payment Intent to the application. The application seems to stop after It opens google chrome browser on android.

My AndroidManifest.xml is as follows-
`
<intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
                <action android:name="android.intent.action.VIEW" /> 
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:scheme="stripesdk"
                    android:host="3ds.stripesdk.io" />
            </intent-filter>
`
The exact prescribed AndroidManifest.xml doesn't even build the app, I applied it this way. If it works in Android full fledged then I'll test it on iOS. Need more insight in it.

**Comment by ezet** [comment]
@Isakdl @vkmaxcooldude Do you have any updates on this issue, what is the current state? I would like to fix these issues, but time is limited, so any help would be appreciated.

**Comment by josxha** [comment]
I also came across the @Isakdl problem where the app is restarted when the authorization process is done with Firefox. This is probably a known problem with deep left of Firefox. I found a quite good solution at https://github.com/NativeScript/android-runtime/issues/712#issuecomment-287708559. They recommend to make the following change in the **AndroidManifest.xml** file: `android:launchMode="singleTask"`

> When this key is set Android will either use the existing instance or open a new one when needed.

For most apps this method will work fine, so we may add this with a note to the [Android](https://github.com/ezet/stripe-sdk#android) section of the **ReadMe.me** file.

**Comment by josxha** [comment]
@ezet I have added `android:launchMode="singleTask"` with a note to the **ReadMe.me** file in my related Pull Request #34.

**Comment by AlexandreRoba** [comment]
Hi all,
deep linking is done using the uni_link package which apparently has some issues on IOS 13+.
[Issue 53](https://github.com/avioli/uni_links/issues/53).
When trying to use the setupintentHandler the browser stay open.
Alex.
