### ISSUE TITLE
Checkout support

### ISSUE THREAD

**Issue by fvisticot** [ezet/stripe-sdk#20]
If I'm correct, the current plugin only allows to pay for a single product. 
It seems not possible to by multiple products with the same session.
Can you please confirm ?

It seems that checkout API feature is required to manage a session with multiple products.
Do you plan to add checkout support ? any roadmap ?

**Comment by ezet** [comment]
The SDK itself provides no facilities or restrictions for sessions. It is definitely possible to use it to buy multiple products at once. There are no plans to support the Checkout API at the moment.
