### ISSUE TITLE
Creating custom Connect account through stripeApi.createToken() method

### ISSUE THREAD

**Issue by lonewsk** [ezet/stripe-sdk#21]
Hi ezet,

Thanks for this library. It is, indeed, very useful.

I'd actually like to use the _createToken_ function to create an account token (for a Stripe custom Connect account) to pass on to my server.
Unfortunately, I can't find a way to pass the _'account'_ argument to call the API correctly.

Here's my code (pretty close to what I'm using in Javascript):
```
var token = stripeApi.createToken({
    'business_type': 'individual',
    'individual': {
      'first_name': firstname,
      'last_name': lastname,
      'email': mail,
      'phone': phone,
      'address': {
        'line1': address,
        'city': city,
        'postal_code': zipcode,
        'state': 'FR',
      },
      'dob':{
        'day': d,
        'month': m,
        'year': y,
      },
    },
    'tos_shown_and_accepted': true,
  });
```

Hence the error I'm getting :

> Unhandled Exception: You must supply either a card, customer, PII data, bank account, or account legal entity to create a token. If you're making this request with a library, be sure to pass all of the required parameters for creating a token. If you're making this request manually, be sure your POST parameters begin with the token type. For example, a PII token would require `pii[personal_id_number]`, while an account token would require a parameter beginning with `account[legal_entity]`. See the API reference for more information: https://stripe.com/docs/api#token_object

Seems like legal_entity is a deprecated argument (see [Stripe API changelog (2019-02-19)](https://stripe.com/docs/upgrades#2019-02-19)). Is this library using an old Stripe API version?

Am I missing something?

Thanks in advance,

lwsk

**Comment by ezet** [comment]
The library uses an API from September I believe, but that can be overridden.

I think you need to wrap your object in another object, with "account" as the key. Ref: https://stripe.com/docs/api/tokens/create_account?lang=node

**Comment by lonewsk** [comment]
Alright, wrapping it up in an "account" object worked for me. Thanks for the help!
