### ISSUE TITLE
Needs a working example

### ISSUE THREAD

**Issue by sgehrman** [ezet/stripe-sdk#22]
I have no idea what to do with your current example.

**Comment by joshuachestang** [comment]
I would agree. We need a working example of CardForm() too.

**Comment by ezet** [comment]
I have a complete working app that I will be adding as an example after some refactoring. 
Meanwhile, you can also check out #24 until its merged.

**Comment by ezet** [comment]
You can find a complete app example here: https://github.com/ezet/glappen-client
