### ISSUE TITLE
american express not trigger cvv 4 digits

### ISSUE THREAD

**Issue by sante85** [ezet/stripe-sdk#25]
If I write amex card 

cvv digits permitted are 3 numbers

example 

378282246310005 | American Express | Any 4 digits | Any future date

**Comment by sante85** [comment]
add listener on change card number to add correct image 
getCardTypeIcon
and correct cvv validation

**Comment by sante85** [comment]
CardNumberFormatter is not implemented

**Comment by ezet** [comment]
> 
> 
> If I write amex card
> 
> cvv digits permitted are 3 numbers
> 
> example
> 
> 378282246310005 | American Express | Any 4 digits | Any future date

I'm not sure I get what you mean. CVV validation currently requires 4 digits for AmEx.
