### ISSUE TITLE
SCA inside the app

### ISSUE THREAD

**Issue by juanluishg** [ezet/stripe-sdk#32]
When you confirm the paymentMethon with 
`    final paymentIntent = await Stripe.instance.confirmSetupIntentWithPaymentMethod(clientSecret, paymentMethod['id']);`

The app open a WebBrowser to confirm the payment, but are there any options to confirm inside the app? with a iframe or with the [ UI of Stripe](https://stripe.com/docs/payments/3d-secure#android) :

**Comment by ezet** [comment]
Not using this library, no. There are other flutter plugins that wrap the android/ios SDKs out there.

**Comment by juanluishg** [comment]
And what plugins can I use?

**Comment by josxha** [comment]
> 
> 
> And what plugins can I use?

@juanluishg Stripe provides a list with all known libraries for their service. 
Have a look at: [https://stripe.com/docs/libraries](https://stripe.com/docs/libraries)

**Comment by ezet** [comment]
You can also just search pub.dev for newer packages.
