### ISSUE TITLE
Only the host part of returnUrl should be customizable

### ISSUE THREAD

**Issue by ezet** [ezet/stripe-sdk#38]
Or assert that the scheme isn't an existing scheme, such as http or https.

**Comment by ezet** [comment]
This would break web support, as it uses a http/https scheme

**Comment by josxha** [comment]
@ezet How about this?
```dart
import 'package:flutter/foundation.dart' show kIsWeb;

assert(!kIsWeb ^ ['http', 'https'].contains(returnUrl.split(':')[0]));
```
see: https://api.flutter.dev/flutter/foundation/kIsWeb-constant.html

This would also make it necessary to use an http / https scheme on the web.
Additionally, instructions about the web implementation could be included in the ReadMe.me for experimental web support (which it already is in principle).

**Comment by ezet** [comment]
Great suggestion, that makes this entirely possible, and can even provide helpful error messages if used incorrectly :)
