### ISSUE TITLE
ClientSeret on the app

### ISSUE THREAD

**Issue by AlexandreRoba** [ezet/stripe-sdk#40]
I looked at the latest version of the API and some method that I used for the SetupIntent have been marked as deprecated (`handleSetupInten`t). 
You have now some new methods fully integrated for this (`confirmSetupIntentWithPaymentMethod` for example). But hose requires the clientSecret as parameter. Isn't this a security issue. Are those keys supposed to be on the mobile app? thanks for your help. Alex

**Comment by ezet** [comment]
`client_secret` is the intended mechanism to work with intents. The use of `next_action` in `handleSetupIntent` is not officially supported, and is really an implementation detail of this particular library. The use of client secret is documented here: https://stripe.com/docs/payments/payment-intents#passing-to-client

In most cases, `Stripe.confirmSetupIntent(client_secret)` is the correct approach.

Can you detail the flow where you used `handleSetupIntent` ? Specifically, the flow between the client, your backend and the Stripe API? That way I might better understand if there is a real need for this method.

**Comment by diegogarciar** [comment]
Hello, I'm here too about the deprecation of `handleSetupIntent`, In my app I was  passing to the function the returned `paymentIntent.next_action`.  Honestly I don't know the correct approach so if you suggest using `Stripe.confirmSetupIntentWithPaymentMethod` and its works,  I'll do that.

 @AlexandreRoba its ok to manage the client secret on the app, but you should not store it though.

**Comment by diegogarciar** [comment]
Ok I reviewed your library and my code, I see that `handleSetupIntent` is used inside `confirmSetupIntent`, I use `handleSetupIntent` because I try to confirm the setupIntent from creation, so I already have the `next_action` variable

**Comment by ezet** [comment]
Thanks for the feedback. I'll make sure to not remove any critical features without a suitable replacement. I understand your usecase, and will provide support for it, but most likely through a breaking change in v3.0

**Comment by diegogarciar** [comment]
Thanks @ezet, and one question, on cloud function call to create the setup intent are you also confirming it on creation?

**Comment by ezet** [comment]
@diegogarciar However, Stripe seems to suggest that you should create your setup intent immediately upon receiving an intent to create a payment method, e.g. when they enter a "add card" screen. And that you later confirm this intent using the collected details. https://stripe.com/docs/payments/save-and-reuse#android-create-setup-intent

> Thanks @ezet, and one question, on cloud function call to create the setup intent are you also confirming it on creation?

That is correct, but I am actually changing this right now, as we speak :D I can push the code in a few minutes, both example and backend is being updated. But I don't seen an issue with doing it your way either, I'm not entirely sure why Stripe suggests creating the empty intent first.

**Comment by ezet** [comment]
@diegogarciar I have updated the example and server code. The example app uses both approaches now. The built-in AddPaymentMethodScreen uses the empty setup intent approach, seen here https://github.com/ezet/stripe-sdk/blob/08f213504a95084677b0f85f8a76d236bea3629d/lib/src/ui/screens/add_payment_method_screen.dart#L90

The stripe test cards use the other approach, where the intent is immediately confirmed with a PM, here: https://github.com/ezet/stripe-sdk/blob/08f213504a95084677b0f85f8a76d236bea3629d/example/lib/setup_intent_with_sca.dart#L45

**Comment by diegogarciar** [comment]
Hey @ezet I'm reviewing your notes as you have removed the handleSetupIntent method,

I already did
` final createSetupIntentResponse = await networkService.createSetupIntentWithPaymentMethod(paymentMethod); ` as in the example you posted above and after that you have

`var setupIntent = await stripe.confirmSetupIntent(createSetupIntentResponse.clientSecret);`

but from my side the function is declared as follow
`confirmSetupIntent(String clientSecret, String paymentMethod)`
but I don't want to include again the payment method as I already created the setup intent with it, I can't comprehend why you were able to do it or if the example is outdated. can it be an optional parameter?

**Comment by diegogarciar** [comment]
is it `authenticateSetupIntent` instead?

**Comment by ezet** [comment]
Yes, authenticate should fit your needs here.
