### ISSUE TITLE
crashes when trying to handle next_action of type: use_stripe_sdk

### ISSUE THREAD

**Issue by Isakdl** [ezet/stripe-sdk#42]
next_action in a paymentIntent can be two different types:

redirect_to_url or use_stripe_sdk. 
https://stripe.com/docs/api/payment_intents/object

only redirect_to_url has a url key. This packages makes the assumption that all next_action are of type redirect_to_url and hence throws an error when parsing use_stripe_sdk. 

Not sure if use_stripe_sdk can be handled in any graceful way? If not it would be helpful to throw a descriptive error instead.

**Comment by ezet** [comment]
"use_stripe_sdk" is not supported, and is only intended for native Stripe mobile SDKs. "use_stripe_sdk" action would only be returned if you specify this during the request, and should not be used in combination with this library.

I agree that I could add a better description for this, will do it in a future update.

**Comment by Isakdl** [comment]
I see, but said paymentIntent was able to be handled by `Stripe.instance.confirmPayment(paymentIntentClientSecret)` why can that function handle it but not `Stripe.instance.authenticatePayment(paymentIntentClientSecret)` ? 

My current flow is creating an off_session payment with a card that requires 3dsecure on all transactions. This paymentIntent gives the use_stripe_sdk next_action. If use_stripe_sdk is set to false I have to set a return url server side which seems a bit strange. Probably something I have missed with the stripe flow.

**Comment by ezet** [comment]
You should set a return URL server-side, pass the url returned by
Stripe.instance.getReturnUrl() do your backend, and use that :)

**Comment by ezet** [comment]
An example of working backend implementations for this is available here: https://github.com/ezet/stripe-sdk-demo-api/blob/master/functions/src/handlers/createManualPaymentIntentHandler.ts

**Comment by ezet** [comment]
The reason `Stripe.instance.confirmPayment(paymentIntentClientSecret)` works is because this method sets the returnUrl during confirmation. While your current server implementation most likely has `contirm=true` (the default) and needs this to be set immediately. In either case, returnUrl must be set before confirmation is attempted.

**Comment by Isakdl** [comment]
I see, thank you very much for the input :)
