### ISSUE TITLE
StripeApiException (You cannot confirm this PaymentIntent because it's missing a payment method.

### ISSUE THREAD

**Issue by newbieflutter** [ezet/stripe-sdk#44]
Hi,
    Sorry I am very new to this integration. I am testing your example at the payment. So when I click Pay button I get this error StripeApiException (You cannot confirm this PaymentIntent because it's missing a payment method. Any help how to go about this ? I have check the logs has clientSecret value and status: requires_payment_method. Anything else is missing in the example?

**Comment by ezet** [comment]
What example are you testing?

**Comment by newbieflutter** [comment]
Hi,
    I am testing the one paying with credit card.

**Comment by ezet** [comment]
Any issues in the example should be fixed now.

**Comment by newbieflutter** [comment]
Hi,
   You are fixing the issue is it ? So when can I test it again?
