### ISSUE TITLE
Feedback: PaymentMethodsScreen

### ISSUE THREAD

**Issue by ezet** [ezet/stripe-sdk#46]
Please provide feedback on PaymentMethodsScreen here.

This is an experimental feature that provides a fully managed payment methods screen/flow.

**Comment by peterjeffrey** [comment]
<img width="920" alt="Screen Shot 2020-04-29 at 8 40 00 AM" src="https://user-images.githubusercontent.com/33112393/80615902-2214c200-89f5-11ea-91ae-53dce854de51.png">

On Flutter Web, the card payment icon is a little off. Any idea how I can fix this? Thanks!

**Comment by ezet** [comment]
Hmm, that certainly looks strange. I use a 3rd party library for the card, https://pub.dev/packages/awesome_card so you'd have to reach out to him.

If it doesn't work well I might have to look for another solution

**Comment by ezet** [comment]
I will remove the dependency on a 3rd party library for this, such that all handling of credit card details will be kept internal to the library. I will also simplify the screen, to make it more inline with the UI of the official SDKs.

**Comment by nyilkhan** [comment]
Any update on this issue?

**Comment by ezet** [comment]
I have not had time to fix this yet, but I'm watching the issue and have a few solutions in mind. Also, contributions for web support would be very welcome.

**Comment by ezet** [comment]
This issue has been fixed, and all other feedback has been addressed. Feature is out of beta.
