### ISSUE TITLE
StripeApiException (The `payment_method` parameter supplied pm_1GcLIZF57NEHJIQ52C0rHX4K belongs to the Customer cus_H8cY8keUuLqMKN. Please include the Customer in the `customer` parameter on the PaymentIntent.)

### ISSUE THREAD

**Issue by loicgeek** [ezet/stripe-sdk#49]
hello guys , I am trying to confirm a payment, but m getting an error,
 var resp = await Stripe.instance.confirmPayment(
            paymentIntent,
            paymentMethodId,
          );

**Comment by josxha** [comment]
While updating my packages I came across the same error. Fortunately the problem is easy to fix:
```dart
var resp = await Stripe.instance.confirmPayment(
    paymentIntentClientSecret,
    paymentMethodId: paymentMethodId,
);
```

Since a recent update, `paymentMethodId` has become an optional parameter. Therefore this adjustment must be made in your implementation.

**Comment by ezet** [comment]
I am not sure the above solution will fix the error in the title. If it doesn't fix it, try setting the `customer` property when creating the payment intent on your backend.

**Comment by josxha** [comment]
@ezet I just looked in the ReadMe.me under [SCA/PSD2](https://github.com/josxha/stripe-sdk#scapsd2) and saw that the old implementation is still documented here.

The line
```dart
final paymentIntent = await Stripe.instance.confirmPayment(clientSecret, "pm_card_visa");
```

needs to get changed to

```dart
final paymentIntent = await Stripe.instance.confirmPayment(
    clientSecret, 
    paymentMethodId: "pm_card_visa",
);
```

**Comment by josxha** [comment]
> 
> 
> I am not sure the above solution will fix the error in the title. If it doesn't fix it, try providing a `customer` parameter when creating the payment intent on your backend.

@ezet Oh right, sorry for my mistake.

**Comment by loicgeek** [comment]
It is solved,the problem was on backend side
