### ISSUE TITLE
Flutter Web Support

### ISSUE THREAD

**Issue by nyilkhan** [ezet/stripe-sdk#51]
Does this plugin currently support Flutter web applications? I am trying to integrate a payment gateway into my Flutter web app and am trying to find this best way to do so.

**Comment by josxha** [comment]
This is actually a duplicate to https://github.com/ezet/stripe-sdk/issues/41.
It should work fine because this package is written completly in dart. Have a look at the mentioned issue for more information.

**Comment by nyilkhan** [comment]
How would I go about adding the UI elements for collecting payment information securely? I know Stripe offers the UI components in JavaScript, but not sure how to add this to my web app.

**Comment by josxha** [comment]
I'm not sure where exactly your problem is, but you might want to take a look at the sample project. It might have what you're looking for: https://github.com/ezet/stripe-sdk/tree/master/example
