### ISSUE TITLE
Payment Method Customization

### ISSUE THREAD

**Issue by nyilkhan** [ezet/stripe-sdk#53]
I am new to Flutter and Stripe and was wondering how would I go about customizing the payment method screen? I am currently using the example on my Flutter web application, and as mentioned before the view looks off. How can I make this look better or get rid of the picture all together?

Any advice on how to make this look better would be appreciated.

<img width="1050" alt="Screen Shot 2020-05-21 at 3 00 39 PM" src="https://user-images.githubusercontent.com/31255060/82595606-db3d6680-9b73-11ea-8881-f09b6d304a6d.png">

**Comment by ezet** [comment]
At the moment, you cannot customize that particular part of the screen. However, what you can do is create own screen by copying the code from the SDK, and then editing the parts you wish to change. I realize this is not ideal, but I have not had much time to work on this recently. I am aware of the issue, and I intend to fix it, but web support isn't high on my priority list at the moment. If someone wants to contribute, I'd be happy to accept PRs.
