### ISSUE TITLE
Unable to click "Return to Merchant" button after 3DS authentication completed in ios

### ISSUE THREAD

**Issue by phj7777777** [ezet/stripe-sdk#54]
It seem like the "Return to Merchant" button was unable to click after 3DS authentication is completed which triggered by confirmPayment method. It is able to return to the app by clicking on "Done" button at the top left. I already added custom URL scheme into info.plist which are exactly same with the one in returnUrlForSca. This issue only occured in IOS as android will directly redirect user back to the app after authentication completed. Need help to check if anyone facing this issue as well. Thanks in advance.

**Comment by josxha** [comment]
Unfortunately I have not yet implemented and tested a complete payment process under iOS. But maybe my guess will help you. The "Done" button only closes Safari so that your app is visible again. However, the payment process of the app is waiting to receive a return url set by you before. This url contains important data that the app needs to continue. 

> I already added custom URL scheme into info.plist which are exactly the same with the one in returnUrlForSca.

But I think that this is where the error could be found. You can try to open a link with your custom url scheme and host on your mobile phone. If the info.plist works, iOS should open the app. If not, you should probably check the info.plist again. However, in this case, the error is not due to Flutter or this library.

I hope you can find the problem. Otherwise, I would ask you to share the contents of your info.plist file with us.

**Comment by phj7777777** [comment]
Hi and thanks for replying. I try to copy the custom scheme url  and yes it able to bring me back to the app. I copied the url of  "Return to Merchant" page and open it in safari app. In Safari App,  the button is worked. So i am actually wondering if the problem would be cause due to using safari view controller?

**Comment by ezet** [comment]
That is likely the issue. I don't own an iOS device, but on Android,
webviews do not support deeplinks, so you need to open the page in a native
browser app.

**Comment by ezet** [comment]
I'm assuming the use of webview was the issue. Please reopen this if I am mistaken.

**Comment by antonkrasov** [comment]
@ezet hey, I had the same issue, here is how I fixed it: https://github.com/antonkrasov/stripe-sdk/commit/80cd1fcc5d9dd806d4b55b986c41cc22a1b182b2

@ezet thanks for your work! I probably have to make a pull request, but not sure if this fix will work for everyone, let's reopen this issue and wait for some feedback?

**Comment by DuncanKelbie** [comment]
@antonkrasov I came to the same solution but it would be nice not to launch an external browser.

I found that instead we can call `closeWebView()` just after `completer.complete(intent)`. It works for me but I've not thoroughly tested it

**Comment by chris-makaio** [comment]
awesome, thanks @DuncanKelbie  - I implemented the setupIntent with 3DS and found it hard to tell the user to tap "done" afterwards. Fortunately, we're already using url_launcher so this is basically the required code as a boilerplate for others and fyi:
```dart

Future<void> setupCreditCard(BuildContext context) async {
    final stripe = Stripe.instance;
    
    /* _createSetupIntentWithPaymentMethod calls our own WebAPI */
    final createSetupIntentResponse = await _createSetupIntentWithPaymentMethod("pm_card_authenticationRequiredOnSetup");

    if (createSetupIntentResponse.status == 'succeeded') {
      /* Created setupIntent w/o confirmation required */
    } else {
      /* Confirmation required, let the lib show the webview */
      var confirm = await stripe.authenticateSetupIntent(createSetupIntentResponse.clientSecret);

      /* confirmation failed / succeeded */
      await closeWebView();
      if (confirm["status"] == 'succeeded') {
        /* setup intent created after confirmation / authentication */
      } else {
        /* show error */
      }
    }
  }

```

**Comment by ezet** [comment]
Interesting, will look into this
