### ISSUE TITLE
Adding optional FormField for cardholder's name

### ISSUE THREAD

**Issue by magnus188** [ezet/stripe-sdk#56]
Would it be possible to create an optional FormField for the cardholder's name in CardForm integrated with the animations on StripeCard that already exists?

**Comment by sondresorbye0111** [comment]
Wow, this would actually be really nice.

**Comment by ezet** [comment]
Probably not, as the card form is a 3rd party library

**Comment by algirdasmac** [comment]
@ezet I think it should be possible because 3rd party library used [awesome_card](https://pub.dev/packages/awesome_card) for this package has this option.

**Comment by ezet** [comment]
I'm looking to remove `awesome_card` as it causes issues on web. The official android SDK from stripe does not include the name in its card widget, and I'm hesitant to spend time on this at the moment.
