### ISSUE TITLE
Failed to retrive ephemeralKey from server

### ISSUE THREAD

**Issue by nordinenn** [ezet/stripe-sdk#57]
Im getting this exception i dont know what im missing please someone help me 

E/flutter ( 9427): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Failed to retrive ephemeralKey from server
E/flutter ( 9427): #0      EphemeralKeyManager.retrieveEphemeralKey .

**Comment by emmaxCreative** [comment]
same error.. how did you fix it ?

**Comment by nordinenn** [comment]
you should updgrade your firebase plan  .
because in free plan you cant call external api.

**Comment by emmaxCreative** [comment]
it is already in the blaze plan. Nevermind. I will try something different then. Thanks.

**Comment by varunbhalerao56** [comment]
hi did anyone find what the issue was, even i am on the blaze plan
