### ISSUE TITLE
Add an option to handle SCA inside webview! 

### ISSUE THREAD

**Issue by lzzy12** [ezet/stripe-sdk#59]
Currently, the library opens a new browser window, but it would be better if there is an option to handle the SCA inside the app itself in a webview window!

**Comment by ezet** [comment]
I agree, but I haven't had time or ability to develop this for the web. PRs are welcome.

**Comment by lzzy12** [comment]
Actually I'm not talking about web at all! I'm talking about Android itself. what I'm suggesting is that instead of opening a browser for SCA , having a webview inside the app which will avoid opening a browser and need for the user to leave the app improving UX.. The `launch` method of `url_launcher` takes in forceWebView and hence I tried doing this: https://github.com/lzzy12/stripe-sdk/commit/e32051e91d1eff4bd82de02a16041acb6ff4bc2d . However after completing the SCA flow, it tries to redirect to the app intent stripesdk://stripe.io but it gives an ERR_UNKNOWN_URL_SCHEME error like this:
![Screenshot_20200615-155014911](https://user-images.githubusercontent.com/26739338/85167132-f4762780-b285-11ea-963a-a8f4179bdfdd.jpg)

**Comment by ezet** [comment]
Ah yes, webviews do not support deep linking. I tried that initially, but
it's not possible.

**Comment by anik786** [comment]
@ezet How about by adding an event listener and monitoring the URL address?

**Comment by lzzy12** [comment]
I tried to modifying the url_launcher plugin to override the `shouldOverrideUrl` method of WebView to call startIntent when the schema of the url is = getReturnUrlForSca(). However it doesn't quite work as it just re starts the app which isn't the expected behavior. I do not have much experience working with Android native. Maybe someone can guide me in the right direction. Here's my modification: https://github.com/lzzy12/plugins/commit/bbc48ff1e74dbd56699ba0ca6a3233c8e4dad8ba

**Comment by lzzy12** [comment]
At this point I might consider just using the webview plugin of flutter to handle SCA on mobile devices

**Comment by anik786** [comment]
@lzzy12 Tell me how it goes

**Comment by ezet** [comment]
@lzzy12 Any progress here? I've tried to get a webview working before and was unable to. I'll close this unless someone has made any progress.

**Comment by lzzy12** [comment]
I didn't get the time to work on it recently.. You can close it for now if you want. Maybe I will reopen it when I make some progress or just send a PR

**Comment by DuncanKelbie** [comment]
@ezet I got webview working. I don't know whether it is a good solution or not but it worked for me.
See my comment at the end of https://github.com/ezet/stripe-sdk/issues/54

**Comment by ezet** [comment]
Web views are not recommended for security-sensitive applications
