### ISSUE TITLE
What parts of the return URL is customisable?

### ISSUE THREAD

**Issue by anik786** [ezet/stripe-sdk#62]
For the return URL, in the docs its:

```
stripesdk://3ds.stripesdk.io
```

On the demo app, you used:
```
stripesdk://demo.stripesdk.ezet.io
```

So what parts of the redirect URL is customisable.

For example could we do this:
```
myfoodapp://myfoodapp.com/stripe/redirect
```

**Comment by josxha** [comment]
Yes you could and actually should. 
A custom url scheme makes sense in any case, unless you use flutter web. Here you should use https.

P.S. Please make sure to add this to your manifest file and info.plist file accordingly.

**Comment by anik786** [comment]
So am I right in saying the entire URL is customisable? Including the scheme?

**Comment by ezet** [comment]
Yes, that is correct

**Comment by anik786** [comment]
Great thanks.
