### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by eliudio** [ezet/stripe-sdk#64]
Hi,

is there a hello world example. It would be good to have a bare minimum example flutter app that just accepts a payment. Plain and simple. Now it looks like a hard task to consider using this plugin. When I open the example app you provide, the first thing I stumble upon is some weird callback. Looks quite complicated to start with. 

I currently use flutter_stripe_payment. My simple use of that plugin is illustrated here: https://github.com/jonasbark/flutter_stripe_payment/issues/182

Thanks,

Eliud

**Comment by ezet** [comment]
The callback is simple and required by the Stripe API. I don't want to encourage bad or insecure practice by providing your secret key directly to the app.
