### ISSUE TITLE
CardForm UI not rendering properly

### ISSUE THREAD

**Issue by jeffaknine** [ezet/stripe-sdk#65]
Hi, I'm using flutter web version 1.19.0-4.3.pre and stripe-sdk version ^2.8.2

When using the CardForm, the UI is not being rendered properly. See the following image
<img width="701" alt="Screen Shot 2020-07-18 at 7 59 35 pm" src="https://user-images.githubusercontent.com/11058286/87858861-3e0f6c00-c931-11ea-92ad-0d7f73d3b577.png">
<img width="701" alt="Screen Shot 2020-07-18 at 8 00 41 pm" src="https://user-images.githubusercontent.com/11058286/87858897-79aa3600-c931-11ea-9b18-e615857de860.png">

**Comment by eswervarma** [comment]
> Hi, I'm using flutter web version 1.19.0-4.3.pre and stripe-sdk version ^2.8.2
> 
> When using the CardForm, the UI is not being rendered properly. See the following image
> <img alt="Screen Shot 2020-07-18 at 7 59 35 pm" width="701" src="https://user-images.githubusercontent.com/11058286/87858861-3e0f6c00-c931-11ea-92ad-0d7f73d3b577.png">
> <img alt="Screen Shot 2020-07-18 at 8 00 41 pm" width="701" src="https://user-images.githubusercontent.com/11058286/87858897-79aa3600-c931-11ea-9b18-e615857de860.png">

Same issue   stripe-sdk version ^2.8.2

**Comment by ezet** [comment]
I'm aware of this. I'll look at replacing or removing this library alltogether

**Comment by jeffaknine** [comment]
Any suggestion of a quickfix in the meantime ?

**Comment by ezet** [comment]
It's not a "quickfix", but you can write your own widget to collect card
details, or use any other library you wish to use. You can then call the
StripeApi with a map of the card details using this library

**Comment by AyoPrez** [comment]
I fixed this problem in a fork that I made of this library and of the "AwesomeCard" library.

In the "AwesomeCard" library, in the file "credit_card.dart", in the line 229, I replace the 3 for a 1

..setEntry(3, 2, 0.001)
..setEntry(1, 2, 0.001)

This fix the visualization problem and the card sees good in all the devices. 

After fixed it I push and I link in this project my version of the "AwesomeCard", and in my app I use my version of this library

**Comment by eswervarma** [comment]
@AyoPrez fixed the same. Not a issue with Stripe-sdk but with the dependency of Awesome card.

**Comment by ezet** [comment]
If you can make the maintainer of awesome_card update the library, I'll update my dependency on it. But I will most likely remove the dependency on that library in the future, and create a basic form to collect details without relying on a 3rd party plugin.
