### ISSUE TITLE
Failed to retrive ephemeralKey from server/ How to use the CustomUserClaims

### ISSUE THREAD

**Issue by varunbhalerao56** [ezet/stripe-sdk#68]
Hi can someone help me with this, i am getting this error when i try to go into customers (note : I am using my stripe account) 

The following assertion was thrown:
An exception was throw by Future<CustomerData> listened by

FutureProvider<CustomerData>, but no `catchError` was provided.

Exception:
Failed to retrive ephemeralKey from server

This is the error message i get in the flutter console 

----------------------------------------------------------------------------------

And this is the error i get in the server side 

Error: Missing customClaims.stripeID for user: 7DcAWNQzikg9FT5o12JiD3gERjA3
    at getStripeCustomerIdForUser (/workspace/lib/utils.js:79:23)
    at Object.getStripeCustomerId (/workspace/lib/utils.js:71:12)
    at process._tickCallback (internal/process/next_tick.js:68:7) 

---------------------------------------------------------------------------------

i already have a document with that id, i know this may be a very easy issue to solve ( i feel using the setCustomUserClaims to make a customer is the solution but i am not sure how to do it) this i my first time working with typescript and cloud functions, if anyone has any form of solution or tip, it will be highly appreciated.

**Comment by ezet** [comment]
I assume you have copied the backend code from my example? I set the
customer id as a user claim, but if you want to store it in a document
instead that's fine too. You just need to update the code to use that
instead of the user claim. You can read about user claims in firebase auth
docs.

**Comment by varunbhalerao56** [comment]
Yep i took your backend code, i have it such that the userID is the document id, and  i created a simple login and register, it seems to be able to call the function to create the user, but in the setupuser function log i keep getting this error 

`Error: Invalid API Key provided: <sk_test*************************************************************************************************nXL>
    at IncomingMessage.res.once (/workspace/node_modules/stripe/lib/StripeResource.js:162:21)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:466:23)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) 
`
Even though i used the firebase functions:config:set stripe.secret_key="<sk_...>" command given in the readme of the backend for your example, and just for assurance i rechecked my secret key but it still kept giving me this error, (Note: when i directly run ur example without putting my key in and without changing any code it works) i am really stuck here, is there anything else i need to do to get it running cause as soon as i put my key in (with or without the login) it  either  gives the error in that i posted originally or the one i am posting now.

**Comment by ezet** [comment]
`functions.config().stripe.secret_key` is a method to read from the firebase function environment, so you would have to set the environment variable for it to work. https://firebase.google.com/docs/functions/config-env
