### ISSUE TITLE
What is locator.dart?

### ISSUE THREAD

**Issue by ollydixon** [ezet/stripe-sdk#73]
The example has some unknown's in it, for example, what is locator.dart?

**Comment by ResoDev** [comment]
The example app is using [get_it](https://pub.dev/packages/get_it) for dependency injection, so `locator.dart` is a service locator.
In this case, it just makes sure that you can access `CloudFunctions` and `NetworkService` as singletons.

**Comment by eyoeldefare** [comment]
> The example has some unknown's in it, for example, what is locator.dart?

Its a service locator using Get. You don't have to use it. You can create your own Service Provider which I will try to show an example sometime soon.
