### ISSUE TITLE
Error: Failed to retrive ephemeralKey from server

### ISSUE THREAD

**Issue by patrickboulay** [ezet/stripe-sdk#76]
Sorry to bug you about this issue but I get this error and I have no idea how to fix it.
I deploy de cloud functions in my existing firebase account (Blaze plan).
I try the app (Flutter web) locally and also hosted in firebase (same project as the cloud functions) and I still get this error.

The only changed I made is the _stripePublishableKey and the region (us-central1).

Do I need to modify something else?

Thanks

**Comment by eyoeldefare** [comment]
1) the ephemeral key comes from your server so you should have a dedicated server of your own that sends the ephemeral key to the client to initialize the customer session as it says in the documentation. 
2) "The only changed I made is the _stripePublishableKey and the region (us-central1)." You also need to follow the stripe API to know how you can create an ephemeral key with your stripe secret key on the server-side.

**Comment by patrickboulay-moonshothealth** [comment]
I use the cloud functions provided by https://github.com/ezet/stripe-sdk-demo-api. But it's seems to be a problem to call the cloud functions(on Flutter side). I am trying the example on Flutter Web, do I need to set a credentials or something like that?

**Comment by patrickboulay-moonshothealth** [comment]
Finally the problem is that I was missing firebase settings in my index.html
https://firebase.flutter.dev/docs/installation/web

My bad, sorry!

**Comment by tstrg** [comment]
If you are using stripe-sdk-demo configured to your Stripe account,  don't forget to adjust Stripe Customer Id to the existing customer id in your Stripe account
https://github.com/ezet/stripe-sdk-demo-api/blob/9e788d3c3b90408c530f55f76de663de4c21eda0/functions/src/utils.ts#L66

**Comment by eyoeldefare** [comment]
@tstrg  Good example

**Comment by CiriousJoker** [comment]
Also, for Flutter web, you need to configure the backend properly, like in my comment here: https://github.com/ezet/stripe-sdk/issues/87 (I'm using the default backend, you can also provide your own)

**Comment by ezet** [comment]
Thank you for all your help and support @eyoeldefare and @CiriousJoker ! I will be spending some time on this project over the next week, let me know which issues you think are most important.
