### ISSUE TITLE
Any plans to add Native Apple / Google Pay?

### ISSUE THREAD

**Issue by jonsamwell** [ezet/stripe-sdk#84]
Thanks for the library it is very useful, do you have any plans to add Apple / Google pay?

**Comment by SathishGovindaraju** [comment]
Would be the perfect complete package if it supports this.

**Comment by ezet** [comment]
I can look into this next! I haven't had time to work on this for a while, but plan to find some time in the next weeks and going forward.

**Comment by DryDoge** [comment]
> I can look into this next! I haven't had time to work on this for a while, but plan to find some time in the next weeks and going forward.

Hello, it would be great to add this functionality :)

**Comment by ezet** [comment]
It seems this shouldn't be too hard. I'm not sure I will have time to add this anytime soon, but based on some quick research it should be completely possible to implement this on your own, using existing google/apple pay plugins, and using the details from those payment methods to create a payment method in Stripe, using this library.

**Comment by funder7** [comment]
@ezet you can take inspiration from stripe_payment package maybe, it supports the feature

**Comment by NarHakobyan** [comment]
Hi @ezet, thanks for writing such a great lib, what about plans to add this feature as well?

**Comment by FallenRiteMonk** [comment]
any update?

**Comment by ezet** [comment]
This is now supported, using https://pub.dev/packages/pay :)
