### ISSUE TITLE
How can I dismiss/clear the current PaymentMethodStore??

### ISSUE THREAD

**Issue by emmaxCreative** [ezet/stripe-sdk#88]
Currently if an user loggs out of my app and logs in as anonymous user  (firebase) he is able to use the creditcards  of the previously logged in user. 

Thats really bad. I tried to end the customer session with `CustomerSession.endCustomerSession();` but that doesn´t seem to help.
I also tried dismissing the PaymentMethodStore. But then the problem is that I cannot use it anymore until i restart the app. 

So my question is. How can I clear the current cards or end a customer session when the signOut button is clicked?

**Comment by emmaxCreative** [comment]
please help its really urgent...

**Comment by CiriousJoker** [comment]
A workaround could be to clear the app data completely when logging out, but that's obviously far from optimal..

**Comment by emmaxCreative** [comment]
The problem is I already clear all stored data. But the paymentMethodStore has no way to be cleared. Even after starting a new customerSession it still holds the creditcards of the logged out account.  After a complete restart of the app it seems to load the new ones.

Another thing is that it sometimes works on Android and I get the correct paymentMethods but it never works on iOS..

**Comment by emmaxCreative** [comment]
nevermind I had to make my own solution of the paymentMethodStore and refresh it with the new CustomerSession because there was no way to do that in the existing one. Its working now after a lot of pain to find the error.

**Comment by ezet** [comment]
I will look at a better solution for this :)

**Comment by ezet** [comment]
There is one solution already supported, which requires that you manage the lifecycle of the store yourself. All methods that use a store optionally accepts a store as a parameter, and by default uses a singleton instance. If you use a DI framework, e.g. `provider` , it should be fairly easy to provide a new store each time a new user signs in.

However, without a DI framework or similar this will be a lot of work to manage, so I'll look for a simpler solution.
