### ISSUE TITLE
Cloud Functions is deprecated 

### ISSUE THREAD

**Issue by maylortaylor** [ezet/stripe-sdk#96]
I'm trying to implement your plugin into my Flutter app and I'm greeted with this warning/error in my `locator.dart` file

'CloudFunctions' is deprecated and shouldn't be used. Constructing CloudFunctions is deprecated, use 'FirebaseFunctions.instance' or 'FirebaseFunctions.instanceFor' instead.  Try replacing the use of the deprecated member with the replacement.

 [Open documentation](https://dart.dev/tools/diagnostic-messages#deprecated_member_use)

**Comment by ezet** [comment]
I'll update this
